- name: Disable NodeJS Default Version
  ansible.builtin.shell: dnf module disable nodejs -y


- name: Enable NodejS 20 Module
  ansible.builtin.shell: dnf module enable nodejs:20 -y


- name: Install Nodejs
  ansible.builtin.dnf: nodejs
  state: latest

APP_PREREQ

- name: include app prereq
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Download NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: {{ app_path }}

- name: load schema
  ansible.builtin.include_role:
    name: common
    tasks_from: schema

- name: setup systemd
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd



