- name: Copy Service file
  ansible.builtin.template:
    remote_src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Start Service
  ansible.builtin.systemd_service:
    name: "{{ component }}"
    state: restarted
    enabled: true
    daemon-reload: true